kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: ClusterIP
  externalName: {{ .Values.ingress.host }}
  ports:
    - port: {{ .Values.docker.port }}
      targetPort: {{ .Values.docker.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
